//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservation.Repository.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class RepositorySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static RepositorySettings defaultInstance = ((RepositorySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RepositorySettings())));
        
        public static RepositorySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{""DayOfTheWeek"":0,""OpenTime"":""09:00:00"",""CloseTime"":""23:00:00""},{""DayOfTheWeek"":1,""OpenTime"":""10:00:00"",""CloseTime"":""22:00:00""},{""DayOfTheWeek"":2,""OpenTime"":""10:00:00"",""CloseTime"":""22:00:00""},{""DayOfTheWeek"":3,""OpenTime"":""10:00:00"",""CloseTime"":""22:00:00""},{""DayOfTheWeek"":4,""OpenTime"":""10:00:00"",""CloseTime"":""22:00:00""},{""DayOfTheWeek"":5,""OpenTime"":""10:00:00"",""CloseTime"":""22:00:00""},{""DayOfTheWeek"":6,""OpenTime"":""09:00:00"",""CloseTime"":""23:00:00""}]")]
        public string BusinessHoursDetail {
            get {
                return ((string)(this["BusinessHoursDetail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{""TableId"":1,""MaxOccupancy"":2},{""TableId"":2,""MaxOccupancy"":2},{""TableId"":3,""MaxOccupancy"":4},{""TableId"":4,""MaxOccupancy"":4},{""TableId"":5,""MaxOccupancy"":4},{""TableId"":6,""MaxOccupancy"":4},{""TableId"":7,""MaxOccupancy"":4},{""TableId"":8,""MaxOccupancy"":4},{""TableId"":9,""MaxOccupancy"":6},{""TableId"":10,""MaxOccupancy"":6}]")]
        public string TableDetail {
            get {
                return ((string)(this["TableDetail"]));
            }
        }
    }
}
